import assert from 'node:assert/strict';
import test from 'node:test';
import { encodeBase58Check, encodeBech32, checksumEvmAddress, convertBits, detectAddress, validateAddressForFamily, validateBitcoinAddress, validateCardanoAddress, validateEvmAddress, validateSolanaAddress } from '../src/shared/addresses.ts';

function syntheticEvmAddress() { return `0x${'ab'.repeat(20)}`; }
function syntheticBase58Address(version) { return encodeBase58Check(new Uint8Array([version, ...new Uint8Array(20).fill(9)])); }
function syntheticExtendedKey(version, prefix = 2) { const payload = new Uint8Array(78); payload.set(version); payload[45] = prefix; payload[46] = 9; return encodeBase58Check(payload); }

test('EVM addresses enforce byte length and EIP-55 mixed-case checksum', () => {
  const lower = syntheticEvmAddress();
  const checksum = checksumEvmAddress(lower);
  assert.equal(validateEvmAddress(lower).ok, true);
  assert.equal(validateEvmAddress(checksum).ok, true);
  const body = checksum.slice(2);
  const index = body.search(/[a-fA-F]/);
  const character = body[index];
  const flipped = character === character.toLowerCase() ? character.toUpperCase() : character.toLowerCase();
  const invalid = `0x${body.slice(0, index)}${flipped}${body.slice(index + 1)}`;
  assert.equal(validateEvmAddress(invalid).ok, false);
  assert.equal(validateEvmAddress('0x123').ok, false);
  assert.equal(validateAddressForFamily(lower, 'evm').family, 'evm');
  assert.equal(detectAddress('x'.repeat(257)).code, 'invalid');
  assert.equal(validateEvmAddress('x'.repeat(257)).message, 'Public address input is too long.');
});

test('Bitcoin Base58Check, Bech32/Bech32m, extended public keys and networks validate offline', () => {
  const mainnet = syntheticBase58Address(0);
  const testnet = syntheticBase58Address(111);
  assert.equal(validateBitcoinAddress(mainnet, 'mainnet').ok, true);
  assert.equal(validateAddressForFamily(mainnet, 'bitcoin').family, 'bitcoin');
  assert.equal(validateAddressForFamily(testnet, 'bitcoin', { network: 'testnet' }).family, 'bitcoin');
  assert.equal(validateAddressForFamily(testnet, 'bitcoin').family, 'bitcoin');
  assert.equal(validateAddressForFamily(testnet, 'bitcoin', { network: 'mainnet' }).ok, false);
  assert.equal(validateBitcoinAddress(syntheticBase58Address(5), 'mainnet').kind, 'p2sh');
  assert.equal(validateBitcoinAddress(mainnet, 'testnet').ok, false);
  assert.equal(validateBitcoinAddress(`${mainnet.slice(0, -1)}1`, 'mainnet').ok, false);
  assert.equal(validateBitcoinAddress(testnet, 'testnet').ok, true);
  const witness = encodeBech32('bc', new Uint8Array(20).fill(5), 0);
  const taproot = encodeBech32('bc', new Uint8Array(32).fill(6), 1);
  const testWitness = encodeBech32('tb', new Uint8Array(32).fill(7), 0);
  assert.equal(validateBitcoinAddress(witness, 'mainnet').ok, true);
  assert.equal(validateBitcoinAddress(taproot, 'mainnet').ok, true);
  assert.equal(validateBitcoinAddress(testWitness, 'testnet').ok, true);
  assert.equal(validateBitcoinAddress(encodeBech32('bc', new Uint8Array(19).fill(8), 0), 'mainnet').ok, false);
  assert.equal(validateBitcoinAddress(encodeBech32('bc', new Uint8Array(2).fill(8), 0), 'mainnet').ok, false);
  assert.equal(validateBitcoinAddress(encodeBech32('bc', new Uint8Array(20).fill(8), 17), 'mainnet').ok, false);
  assert.equal(validateBitcoinAddress('bc1!invalid', 'mainnet').ok, false);
  const xpub = syntheticExtendedKey(new Uint8Array([4, 136, 178, 30]));
  const ypub = syntheticExtendedKey(new Uint8Array([4, 157, 124, 178]));
  const zpub = syntheticExtendedKey(new Uint8Array([4, 178, 71, 70]));
  const tpub = syntheticExtendedKey(new Uint8Array([4, 53, 135, 207]));
  const upub = syntheticExtendedKey(new Uint8Array([4, 74, 82, 98]));
  const vpub = syntheticExtendedKey(new Uint8Array([4, 95, 28, 246]));
  assert.equal(validateBitcoinAddress(xpub, 'mainnet', 'xpub').ok, true);
  assert.equal(validateBitcoinAddress(ypub, 'mainnet', 'ypub').ok, true);
  assert.equal(validateBitcoinAddress(zpub, 'mainnet', 'zpub').ok, true);
  assert.equal(validateBitcoinAddress(tpub, 'testnet', 'tpub').ok, true);
  assert.equal(validateBitcoinAddress(upub, 'testnet', 'upub').ok, true);
  assert.equal(validateBitcoinAddress(vpub, 'testnet', 'vpub').ok, true);
  assert.equal(validateBitcoinAddress(ypub, 'mainnet', 'xpub').ok, false);
  assert.equal(validateBitcoinAddress(xpub, 'mainnet').ok, false);
  assert.equal(validateBitcoinAddress(xpub, 'testnet', 'xpub').ok, false);
  const invalidKey = syntheticExtendedKey(new Uint8Array([4, 136, 178, 30]), 1);
  assert.equal(validateBitcoinAddress(invalidKey, 'mainnet', 'xpub').ok, false);
  assert.equal(validateBitcoinAddress('', 'mainnet').ok, false);
  assert.equal(detectAddress(xpub).family, 'bitcoin');
  assert.equal(detectAddress(ypub).family, 'bitcoin');
  assert.equal(detectAddress(upub).family, 'bitcoin');
});

test('Solana and Cardano validators decode bytes and verify Bech32 checksums', () => {
  const solana = '1'.repeat(32);
  assert.equal(validateSolanaAddress(solana).ok, true);
  assert.equal(validateSolanaAddress('1'.repeat(31)).ok, false);
  const cardanoBytes = new Uint8Array(57); cardanoBytes[0] = 0x01; cardanoBytes.fill(4, 1);
  const rewardBytes = new Uint8Array(29); rewardBytes[0] = 0xe0; rewardBytes.fill(5, 1);
  const cardano = encodeBech32('addr', cardanoBytes);
  const cardanoTest = encodeBech32('stake_test', new Uint8Array([0xe0, ...new Uint8Array(28).fill(5)]));
  const rewardMain = encodeBech32('stake', new Uint8Array([0xe1, ...new Uint8Array(28).fill(6)]));
  const rewardScript = encodeBech32('stake', new Uint8Array([0xf1, ...new Uint8Array(28).fill(6)]));
  const enterprise = encodeBech32('addr', new Uint8Array([0x61, ...new Uint8Array(28).fill(7)]));
  const pointer = encodeBech32('addr', new Uint8Array([0x41, ...new Uint8Array(28).fill(8), 0, 0, 0]));
  const invalidHeader = encodeBech32('addr', new Uint8Array([0x81, ...new Uint8Array(28).fill(8)]));
  const networkMismatch = encodeBech32('addr', new Uint8Array([0x00, ...new Uint8Array(56).fill(8)]));
  assert.equal(validateCardanoAddress(cardano).network, 'mainnet');
  assert.equal(validateCardanoAddress(cardanoTest).network, 'testnet');
  assert.equal(validateCardanoAddress(cardanoTest).kind, 'stake');
  assert.equal(validateCardanoAddress(rewardMain).network, 'mainnet');
  assert.equal(validateCardanoAddress(rewardScript).kind, 'stake');
  assert.equal(validateCardanoAddress(enterprise).ok, true);
  assert.equal(validateCardanoAddress(pointer).ok, true);
  assert.equal(validateCardanoAddress(invalidHeader).ok, false);
  assert.equal(validateCardanoAddress(networkMismatch).ok, false);
  assert.equal(validateCardanoAddress(cardano, 'testnet').ok, false);
  assert.equal(validateCardanoAddress(encodeBech32('addr', new Uint8Array(1).fill(2))).ok, false);
  assert.equal(validateCardanoAddress(encodeBech32('addr', new Uint8Array())).ok, false);
  assert.equal(validateCardanoAddress(encodeBech32('addr', rewardBytes)).ok, false);
  assert.equal(validateCardanoAddress(encodeBech32('addr', new Uint8Array([0x41, ...new Uint8Array(28).fill(8), 0x80]))).ok, false);
  assert.equal(validateCardanoAddress(encodeBech32('addr', new Uint8Array([0x41, ...new Uint8Array(28).fill(8)]))).ok, false);
  assert.equal(validateCardanoAddress(encodeBech32('addr', new Uint8Array([0x41, ...new Uint8Array(28).fill(8), 0xff, 0xff, 0xff, 0xff, 0x7f]))).ok, false);
  assert.equal(validateCardanoAddress(encodeBech32('stake', cardanoBytes)).ok, false);
  assert.equal(validateCardanoAddress(`${cardano.slice(0, -1)}q`).ok, false);
  assert.equal(detectAddress(solana).family, 'solana');
  assert.equal(detectAddress(cardano).family, 'cardano');
  assert.equal(validateAddressForFamily(solana, 'solana').family, 'solana');
  assert.equal(validateAddressForFamily(cardano, 'cardano').family, 'cardano');
  const invalid = detectAddress('not-an-address');
  assert.equal(invalid.ok, false);
  if (!invalid.ok) assert.equal(invalid.code, 'invalid');
  const ambiguous = detectAddress('synthetic', [{ ok: true, family: 'evm', normalized: 'synthetic' }, { ok: true, family: 'solana', normalized: 'synthetic' }]);
  assert.equal(ambiguous.ok, false);
  if (!ambiguous.ok) assert.equal(ambiguous.code, 'ambiguous');
  assert.equal(convertBits([1], 5, 8, false), null);
  assert.equal(convertBits([32], 5, 8, false), null);
  assert.equal(validateAddressForFamily('bad', 'bitcoin', { network: 'testnet' }).ok, false);
  assert.equal(validateBitcoinAddress('x'.repeat(257)).code, 'invalid');
  assert.equal(validateSolanaAddress('x'.repeat(257)).code, 'invalid');
  assert.equal(validateCardanoAddress('x'.repeat(257)).code, 'invalid');
});
