import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { JSDOM } from 'jsdom';
import { createRendererController } from '../src/renderer/renderer-app.ts';

const success = value => ({ ok: true, value });
const flush = () => new Promise(resolve => setImmediate(resolve));
async function fixture() {
  const html = await readFile(new URL('../src/renderer/index.html', import.meta.url), 'utf8');
  const dom = new JSDOM(html, { url: 'file:///holdvue/index.html' });
  for (const dialog of dom.window.document.querySelectorAll('dialog')) { dialog.showModal = () => { dialog.open = true; }; dialog.close = () => { dialog.open = false; }; }
  return dom;
}
function state() {
  const instrument = { schemaVersion: 4, id: 'dom-instrument', providerId: 'fmp.market', providerSymbol: 'SYN@X', symbol: 'SYN', name: 'Synthetic Holding', exchange: 'X', currency: 'EUR', type: 'etf' };
  const quote = { assetId: 'instrument:dom-instrument', priceEurScaled: '1230000000000', priceUsdScaled: '1300000000000', scale: 12, change24hPercentScaled: '50000', change24hEurPercentScaled: '50000', change24hUsdPercentScaled: '40000', previousPriceEurScaled: '1170000000000', previousPriceUsdScaled: '1240000000000', source: 'synthetic', sourceTimestamp: null, fetchedAt: 2 };
  const valuation = { assetId: quote.assetId, quantityBaseUnits: '123', quantityDecimals: 2, priceEurScaled: quote.priceEurScaled, priceUsdScaled: quote.priceUsdScaled, valueEurScaled: '1512900000000', valueUsdScaled: '1599000000000', dayChangeEurScaled: '60000000000', dayChangeUsdScaled: '60000000000', dayChangePercentScaled: '50000', status: 'valued' };
  const point = (timestamp, eur, usd) => ({ timestamp, valueEurScaled: eur, valueUsdScaled: usd, coverage: 'complete' });
  return { schemaVersion: 5, settings: { schemaVersion: 5, currency: 'EUR', locale: 'de', theme: 'dark', schedulerEnabled: true, spamFilterEnabled: true, showHiddenSpamAssets: false, enabledChainIds: [], customChains: [], rpcOverrides: [], providerRefs: [], providerEndpoints: [], enabledProviderIds: [], hiddenAssetIds: [] }, wallets: [], positions: [], instruments: [instrument], holdings: [{ schemaVersion: 4, id: 'dom-holding', instrumentId: instrument.id, quantityHundredths: '123', quantity: '1.23', updatedAt: 1 }], sync: { schemaVersion: 1, statuses: [] }, prices: { quotes: [quote], statuses: [{ assetId: quote.assetId, providerId: 'fmp.market', status: 'ok', errorCode: null, lastGoodFetchedAt: 2 }], valuations: [valuation], history: [{ id: 'portfolio', kind: 'portfolio-value', points: [point(1, '1000000000000', '1100000000000'), point(2, '1100000000000', '1200000000000')] }, { id: quote.assetId, kind: 'asset-price', points: [point(1, quote.priceEurScaled, quote.priceUsdScaled), point(2, '1300000000000', '1400000000000')] }], totalEurScaled: valuation.valueEurScaled, totalUsdScaled: valuation.valueUsdScaled, complete: true, valuedAssets: 1, totalAssets: 1, dayChangeEurScaled: valuation.dayChangeEurScaled, dayChangeUsdScaled: valuation.dayChangeUsdScaled, dayChangePercentScaled: valuation.dayChangePercentScaled } };
}

test('portfolio DOM flow switches currency, ranges, disclosure, exact quantity and confirmed delete', async () => {
  const dom = await fixture(); let current = state(); let observerCallback = null;
  class FakeResizeObserver { constructor(callback) { observerCallback = callback; } observe() {} disconnect() {} }
  const previousObserver = globalThis.ResizeObserver; globalThis.ResizeObserver = FakeResizeObserver;
  const api = { async getState() { return success(current); }, async updateSettings(patch) { current = { ...current, settings: { ...current.settings, ...patch } }; return success(current); }, async deleteHolding(id) { current = { ...current, holdings: current.holdings.filter(item => item.id !== id), instruments: [] }; return success(current); }, async addHolding() { return success(current); }, async updateHolding() { return success(current); }, async searchInstruments() { return success([]); }, async detectWalletAddress() { return { ok: false, code: 'invalid', message: 'synthetic' }; }, async addWallet() { return success(current); }, async updateWallet() { return success(current); }, async deleteWallet() { return success(current); }, async copyWalletAddress() { return success({ copied: true }); }, async setEtherscanKey() { return success(current); }, async deleteEtherscanKey() { return success(current); }, async setFmpKey() { return success(current); }, async deleteFmpKey() { return success(current); }, async refresh() { return success(current); }, onMinute() { return () => undefined; } };
  try {
    const controller = createRendererController(dom.window.document, api); const dispose = controller.start(); await controller.render();
    assert.match(dom.window.document.querySelector('[data-portfolio-total]').textContent, /1,51 EUR/);
    assert.match(dom.window.document.querySelector('[data-portfolio-day]').textContent, /\+/);
    assert.match(dom.window.document.querySelector('[data-portfolio-day]').className, /positive/);
    assert.ok(dom.window.document.querySelector('.balance-panel')); assert.ok(dom.window.document.querySelector('.management-grid')); assert.ok(dom.window.document.querySelector('.asset-list-heading'));
    dom.window.document.querySelector('[data-portfolio-range="MAX"]').click(); assert.equal(dom.window.document.querySelector('[data-portfolio-range="MAX"]').getAttribute('aria-pressed'), 'true');
    dom.window.document.querySelector('[data-currency-switch="USD"]').click(); await flush(); assert.match(dom.window.document.querySelector('[data-portfolio-total]').textContent, /USD/); assert.equal(dom.window.document.querySelector('[data-currency-switch="USD"]').getAttribute('aria-pressed'), 'true');
    const disclosure = dom.window.document.querySelector('[data-asset-disclosure]'); assert.equal(disclosure.hasAttribute('aria-controls'), false); disclosure.focus(); disclosure.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); disclosure.click(); assert.equal(dom.window.document.querySelector('[data-asset-chart]').hidden, false); assert.equal(dom.window.document.querySelector('[data-asset-disclosure]').getAttribute('aria-expanded'), 'true'); assert.ok(dom.window.document.querySelector('[data-asset-disclosure]').hasAttribute('aria-controls')); assert.ok(dom.window.document.querySelector('.asset-detail-chart')); assert.ok(dom.window.document.querySelector('.account-breakdown')); assert.ok(dom.window.document.querySelector('.disclosure-chevron use[href="#icon-chevron-right"]'));
    const valueToggle = dom.window.document.querySelector('[data-asset-toggle]'); valueToggle.focus(); valueToggle.click(); assert.match(dom.window.document.querySelector('[data-asset-toggle]').textContent, /1\.23/); assert.equal(dom.window.document.activeElement, dom.window.document.querySelector('[data-asset-toggle]')); dom.window.document.querySelector('[data-asset-toggle]').click();
    const assetRange = dom.window.document.querySelector('[data-asset-range][data-range="7D"]'); assetRange.focus(); assetRange.click(); assert.equal(dom.window.document.querySelector('[data-asset-range][data-range="7D"]').getAttribute('aria-pressed'), 'true'); assert.equal(dom.window.document.activeElement, dom.window.document.querySelector('[data-asset-range][data-range="7D"]'));
    observerCallback?.(); observerCallback?.(); await flush();
    current.prices.history = [{ id: 'portfolio', kind: 'portfolio-value', points: [{ timestamp: 1, valueEurScaled: '1000000000000', valueUsdScaled: '1100000000000', coverage: 'complete' }, { timestamp: 2, valueEurScaled: '1100000000000', valueUsdScaled: '1200000000000', coverage: 'complete' }] }, { id: 'instrument:dom-instrument', kind: 'asset-price', points: [{ timestamp: 1, valueEurScaled: '1230000000000', valueUsdScaled: '1300000000000', coverage: 'complete' }] }]; await controller.render();
    dom.window.document.querySelector('[data-asset-range][data-range="MAX"]').click();
    current.prices.history = [{ id: 'portfolio', kind: 'portfolio-value', points: [{ timestamp: 1, valueEurScaled: '1000000000000', valueUsdScaled: '1100000000000', coverage: 'complete' }, { timestamp: 2, valueEurScaled: '1100000000000', valueUsdScaled: '1200000000000', coverage: 'complete' }] }]; await controller.render();
    dom.window.document.querySelector('[data-asset-disclosure]').click(); dom.window.document.querySelector('[data-asset-disclosure]').click();
    dom.window.document.querySelector('[data-portfolio-holding-delete]').click(); assert.equal(dom.window.document.querySelector('[data-holding-delete-dialog]').hidden, false); dom.window.document.querySelector('[data-holding-delete-confirm]').click(); await flush(); assert.equal(current.holdings.length, 0);
    current = { ...current, instruments: [], holdings: [], wallets: [{ schemaVersion: 3, id: 'dom-wallet', label: 'Synthetic wallet', family: 'evm', address: `0x${'e'.repeat(40)}`, enabled: true, createdAt: 1, options: { autoScanCommonChains: true, chainIds: [] } }], positions: [{ schemaVersion: 3, id: 'dom-position', walletId: 'dom-wallet', family: 'evm', chainId: 1, assetKind: 'native', assetId: 'native:synthetic', symbol: 'SYN', baseUnits: '1', quantity: '0.000000000000000001', confirmedBaseUnits: '1', pendingBaseUnits: '0', decimals: 18, updatedAt: 1, spam: null }], prices: { quotes: [], statuses: [], valuations: [], history: [], totalEurScaled: null, totalUsdScaled: null, complete: false, valuedAssets: 0, totalAssets: 0, dayChangeEurScaled: null, dayChangeUsdScaled: null, dayChangePercentScaled: null } };
    current.prices = { quotes: [{ assetId: 'asset:evm:1:native:native:synthetic', priceEurScaled: '1000000000000', priceUsdScaled: '1100000000000', scale: 12, change24hPercentScaled: '-10000', change24hEurPercentScaled: '-10000', change24hUsdPercentScaled: '-10000', previousPriceEurScaled: '1010000000000', previousPriceUsdScaled: '1110000000000', source: 'synthetic', sourceTimestamp: null, fetchedAt: 2 }], statuses: [], valuations: [{ assetId: 'asset:evm:1:native:native:synthetic', quantityBaseUnits: '1', quantityDecimals: 18, priceEurScaled: '1000000000000', priceUsdScaled: '1100000000000', valueEurScaled: '5000000000', valueUsdScaled: '5000000000', dayChangeEurScaled: '-1', dayChangeUsdScaled: '-1', dayChangePercentScaled: '-10000', status: 'valued' }], history: [] , totalEurScaled: '5000000000', totalUsdScaled: '5000000000', complete: true, valuedAssets: 1, totalAssets: 1, dayChangeEurScaled: '-1', dayChangeUsdScaled: '-1', dayChangePercentScaled: '-10000' };
    delete current.settings.hiddenAssetIds; await controller.render(); assert.ok(dom.window.document.querySelector('[data-asset-hide] use[href="#icon-eye-off"]')); assert.match(dom.window.document.querySelector('[data-asset-hide]').getAttribute('aria-label'), /Asset ausblenden · /); assert.equal(dom.window.document.querySelector('.asset-price').getAttribute('data-mobile-label'), 'Stückpreis'); assert.match(dom.window.document.querySelector('[data-portfolio-day]').className, /negative/); assert.match(dom.window.document.querySelector('.asset-change').className, /negative/);
    current.prices.history = [{ id: 'portfolio', kind: 'portfolio-value', points: [{ timestamp: 1, valueEurScaled: '1000000000000', valueUsdScaled: '1000000000000', coverage: 'complete' }] }]; await controller.render();
    current.prices.history = [{ id: 'portfolio', kind: 'portfolio-value', points: [{ timestamp: 1, valueEurScaled: '0', valueUsdScaled: '0', coverage: 'partial' }, { timestamp: 2, valueEurScaled: '1', valueUsdScaled: '1', coverage: 'partial' }] }]; await controller.render();
    current.prices.history = [{ id: 'portfolio', kind: 'portfolio-value', points: [{ timestamp: 1, valueEurScaled: '2', valueUsdScaled: '2', coverage: 'partial' }, { timestamp: 2, valueEurScaled: '1', valueUsdScaled: '1', coverage: 'partial' }] }]; await controller.render();
    dom.window.document.querySelector('[data-asset-hide]').focus(); dom.window.document.querySelector('[data-asset-hide]').click(); await flush(); assert.equal(current.settings.hiddenAssetIds.length, 1); assert.equal(dom.window.document.activeElement, dom.window.document.querySelector('[data-add-holding]')); await controller.render();
    observerCallback?.(); dispose();
  } finally { if (previousObserver) globalThis.ResizeObserver = previousObserver; else delete globalThis.ResizeObserver; }
});
